/**
 * widget-map.ts
 *
 * Maps a demo-page slug to the CSS selector of its PRIMARY widget — the thing
 * that page exists to demo. The smoke test asserts this selector is present,
 * outside campaign containers, and renders non-empty content.
 *
 * Resolution order for a slug:
 *   1. WIDGET_OVERRIDES[slug]          — explicit selector below
 *   2. `.elementor-widget-eael-<slug>` — the auto-derived default
 *      (works for ~60 of the current demos, e.g. advanced-search →
 *       .elementor-widget-eael-advanced-search)
 *   3. If the slug is in GENERIC_ONLY, no primary-widget assertion is made —
 *      only the generic "page has ≥1 non-empty .elementor-widget" check.
 *   4. Otherwise (unknown slug, e.g. a brand-new demo page) the missing
 *      selector is reported as a WARNING ("unmapped widget — add it to
 *      widget-map.ts"), not a failure, so new demos never break the build
 *      before they're mapped.
 *
 * ➜ Adding a new demo: usually nothing to do (rule 2 covers it). If the
 *   widget's internal name differs from the page slug, add one line to
 *   WIDGET_OVERRIDES. Find the class by opening the demo page and inspecting
 *   the widget wrapper: <div class="... elementor-widget-eael-XYZ ...">.
 *
 * This map was generated by crawling every Elements Panel link on 2026-07-02
 * and verified against the live pages.
 */

/** Slug → primary-widget CSS selector, where the auto-derived class is wrong. */
export const WIDGET_OVERRIDES: Record<string, string> = {
  // widget internal name differs from the page slug
  'advanced-accordion': '.elementor-widget-eael-adv-accordion',
  'advanced-google-map': '.elementor-widget-eael-google-map',
  'advanced-tabs': '.elementor-widget-eael-adv-tabs',
  'advanced-tooltip': '.eael-section-tooltip', // extension applied to sections
  'caldera-forms': '.elementor-widget-eael-caldera-form',
  'call-to-action': '.elementor-widget-eael-cta-box',
  'content-protection': '[class*="protected-content"]',
  'content-toggle': '.elementor-widget-eael-toggle',
  'creative-buttons': '.elementor-widget-eael-creative-button',
  'dual-color-headline': '.elementor-widget-eael-dual-color-header',
  'dynamic-gallery': '.elementor-widget-eael-dynamic-filterable-gallery',
  'fluent-forms': '.elementor-widget-eael-fluentform',
  'gravity-forms': '.elementor-widget-eael-gravity-form',
  'instagram-feed': '.elementor-widget-eael-instafeed',
  'interactive-cards': '.elementor-widget-eael-interactive-card',
  'learndash-course-list': '.elementor-widget-eael-learn-dash-course-list',
  'lightbox-modal': '.elementor-widget-eael-lightbox',
  'login-register-form': '.elementor-widget-eael-login-register',
  'ninja-forms': '.elementor-widget-eael-ninja',
  'offcanvas-content': '.elementor-widget-eael-offcanvas',
  'table': '.elementor-widget-eael-data-table',
  'team-members': '.elementor-widget-eael-team-member',
  'team-members-carousel': '.elementor-widget-eael-team-member-carousel',
  'testimonials': '.elementor-widget-eael-testimonial',
  'weforms': '.elementor-widget-eael-weform',
  'woo-product-grid': '.elementor-widget-eicon-woocommerce', // yes, really — EA's internal name
  'woocommerce-product-collections': '.elementor-widget-eael-woo-collections',
};

/**
 * Slugs with NO dedicated widget markup — mostly EXTENSION demos (features
 * applied via attributes, not widgets) and the panel's footer links (docs,
 * support, …). These pages only get the generic Elementor-content check
 * plus all PHP/JS/network checks.
 */
export const GENERIC_ONLY: string[] = [
  // extension demos — feature is applied to other elements, no own widget class
  'conditional-display',
  'cross-domain-copy-paste',
  'custom-js',
  'duplicator',
  'parallax-scrolling',
  'particle-effect',    // detectable via [data-particle_enable="true"] if you ever want a stricter check
  'reading-progress',
  'scroll-to-top',
  'table-of-content',
  'wrapper-link',
  'dynamic-tags',
  'custom-cursor',
  // demo pages with no matching first-party widget class on the page today
  'formstack',          // TODO: map once the Formstack demo exposes a stable class
  // panel footer links — not widget demos
  'demos',
  'docs',
  'docs/advanced-search',
  'docs/getting-started/installing-plugin',
  'support',
  'feature-request',
  'changelog',
];

/**
 * Slugs VERIFIED (against the live site) to carry the auto-derived
 * `.elementor-widget-eael-<slug>` class. For these, a missing/empty widget is
 * a build FAILURE. Auto-derived selectors for slugs NOT in this list (i.e.
 * brand-new demos) are only asserted as WARNINGS until someone verifies the
 * class and adds the slug here (or to WIDGET_OVERRIDES / GENERIC_ONLY).
 */
export const VERIFIED_AUTO: string[] = [
  'advanced-data-table', 'advanced-menu', 'advanced-search',
  'betterdocs-category-box', 'betterdocs-category-grid', 'betterdocs-search-form',
  'business-reviews', 'contact-form-7', 'content-ticker', 'content-timeline',
  'countdown', 'counter', 'divider', 'event-calendar', 'facebook-feed',
  'fancy-chart', 'fancy-text', 'feature-list', 'filterable-gallery', 'flip-box',
  'flip-carousel', 'image-accordion', 'image-comparison', 'image-hotspots',
  'image-scroller', 'info-box', 'interactive-circle', 'interactive-promo',
  'logo-carousel', 'mailchimp', 'nft-gallery', 'one-page-nav', 'post-block',
  'post-carousel', 'post-grid', 'post-list', 'post-timeline', 'price-menu',
  'pricing-table', 'progress-bar', 'protected-content', 'simple-menu',
  'static-product', 'sticky-video', 'svg-draw', 'testimonial-slider', 'tooltip',
  'twitter-feed', 'twitter-feed-carousel', 'typeform', 'woo-account-dashboard',
  'woo-cart', 'woo-checkout', 'woo-cross-sells', 'woo-product-carousel',
  'woo-product-compare', 'woo-product-gallery', 'woo-product-list',
  'woo-product-slider', 'woo-thank-you', 'wpforms',
];

export interface WidgetExpectation {
  selector: string | null;   // null → generic Elementor-content check only
  /** true → missing/empty widget FAILS the build; false → warning only */
  strict: boolean;
}

/** Resolve the expected primary-widget selector for a slug (see rules above). */
export function expectedWidget(slug: string): WidgetExpectation {
  if (WIDGET_OVERRIDES[slug]) return { selector: WIDGET_OVERRIDES[slug], strict: true };
  if (GENERIC_ONLY.includes(slug)) return { selector: null, strict: false };
  return {
    selector: `.elementor-widget-eael-${slug}`,
    strict: VERIFIED_AUTO.includes(slug),
  };
}
